- OWNERS
- test.md
> Add OWNERS file

- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
Update the sample devfile URL to be based on https://github.com/redhat-developer/devfile-sample. The port number is adjusted in the test URL.
Tested locally by using Cypress.
> Update the sample devfile URL for dev console tests 

- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
Use https://github.com/redhat-developer/devfile-sample instead of a private repo for tests
> Update test devfile git repo

- openshift-ci/build-root/Dockerfile
Changing golang url as openshift has moved all jobs from api.ci
> Golang pull image error

- scripts/openshiftci-presubmit-devfiles-odo-tests.sh
Fix periodic integration test failure for ODO due to the recent changes in ODO script.
> Bring in new changes from ODO to integration test

- scripts/openshiftci-presubmit-devfiles-odo-tests.sh
> Update the path to the test reports

- scripts/openshiftci-presubmit-devfiles-odo-all-tests.sh
remove an unnecessary line from a test script
> remove an unnecessary line from test script

- scripts/openshiftci-presubmit-devfiles-odo-all-tests.sh
- tests/integration/devfile/cmd_devfile_catalog_test.go
- tests/integration/devfile/cmd_devfile_create_test.go
- tests/integration/devfile/cmd_devfile_push_test.go
- tests/integration/devfile/cmd_devfile_registry_test.go
- tests/integration/devfile/devfile_suite_test.go
Run Odo integration tests with OCI-based staging repository
> Run odo test with OCI staging repsitory

- openshift-ci/build-root/console/Dockerfile
- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
- scripts/console/test-prow-e2e.sh
- scripts/openshiftci-presubmit-devfiles-odo-all-tests.sh
Fixes https://github.com/devfile/api/issues/478
> Update ODC integration tests with the latest changes. 

- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
Add back an existing test case with the latest update from ODC repository.  
https://github.com/devfile/api/issues/478
> Add back a test case - create the workload from dev file

- scripts/console/test-cypress.sh
- scripts/openshiftci-presubmit-devfiles-console-tests.sh
Fix CI build failure issue caused by refactoring in console repository. 
Fixes https://github.com/devfile/api/issues/544
Pull request build covers the required test.
> Fix CI build failure caused by refactoring in console repository

- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
Add back a test case which was disabled for the intermittent issue. 
It passed this PR build test.
> Add back test case with sample link

- README.md
> Update with the correct path in Readme

- OWNERS
- local/odo/tests/integration/devfile/cmd_devfile_catalog_test.go
- local/odo/tests/integration/devfile/cmd_devfile_create_test.go
- local/odo/tests/integration/devfile/cmd_devfile_registry_test.go
Update Odo tests by merging the latest changes in odo repository.
> Update Odo tests by merging latest changes

- README.md
- openshift-ci/build-root/Dockerfile
- openshift-ci/build-root/console/Dockerfile
> Bump up go version to 1.16

- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
Update the integration test to use 2.2.0 sample
> Use devfile 2.2.0 sample

- README.md
Update Readme for newly added pytest
https://github.com/devfile/api/issues/754
> Update Readme for pytest

- README.md
Readme update for pytest
https://github.com/openshift/release/pull/25931
> Readme update for pytest

- tests/test_dot_devfile_cmd.py
Odo test to check compatibility with .devfile.xml. Operations should be done with .devfile.yaml as devfile without using the --devfile flag.
https://github.com/devfile/api/issues/790
Tested locally and by using Github Actions' pytest.
> Add compatibility test with .devfile.xml

- README.md
- tests/test_build_images_cmd.py
- tests/test_deploy_cmd.py
Add odo outer-loop command tests including odo deploy and build-images tests with devfile
https://github.com/devfile/api/issues/795
Tested locally and by Github Actions tests.
> add odo deploy and odo build-images tests

- .github/workflows/pytest.yaml
- tests/test_catalog_cmd.py
- tests/test_url_cmd.py
Bug fix for Odo catalog command test
https://github.com/devfile/api/issues/754
Tested by PR test run.
> Bug fix for Odo catalog command test

- .github/workflows/pytest.yaml
- tests/examples/source/devfiles/nodejs/devfile-variables.yaml
- tests/examples/source/devfiles/nodejs/devfile-with-projects.yaml
- tests/examples/source/devfiles/nodejs/devfileSourceMapping.yaml
- tests/test_deploy_cmd.py
- tests/test_push_cmd.py
- tests/utils/util.py
Add test cases for odo push command with devfile
https://github.com/devfile/api/issues/806
Tested locally and by PR test.
> Add odo push command test with devfile

- .github/workflows/pytest.yaml
- tests/examples/source/devfiles/nodejs/devfile-outerloop-project_source-in-docker-build-context.yaml
- tests/examples/source/devfiles/nodejs/devfile-with-two-deploy-commands.yaml
- tests/test_deploy_cmd.py
Test odo deploy command with devfile containing an Image component with a build context
https://github.com/devfile/api/issues/795
> Add odo deploy test with devfile containing an Image component with a build context

- .github/workflows/pytest_odo.251.yaml
- tests/odo/test_create_cmd.py
- tests/odo_300/test_delete_cmd.py
- tests/odo_300/test_init_cmd.py
Update odo init integration test with devfile. 
https://github.com/devfile/api/issues/828
Tested locally and via PR tests.
> Update odo init test with devfile

- tests/v2/integrationTest/integration_test.go
Enhance and optimize the test codes
https://github.com/devfile/api/issues/850
Tested locally and by PR test.
> Enhance and optimize the test codes

- .github/workflows/pytest.yaml.disabled
- .github/workflows/pytest_odo.250.yaml.disabled
- .github/workflows/pytest_odo.251.yaml
- .github/workflows/pytest_odo.300.yaml
Signed-off-by: Kim Tsao <ktsao@redhat.com>
Updates the license headers in a number of files 
https://github.com/devfile/api/issues/863
> integration-tests license updates

- openshift-ci/build-root/Dockerfile
Update go version to 1.17 for Odo tests
> Update go version to 1.17 for Odo tests

- local/odo/Makefile
- local/odo/odo-integration-tests.sh
- openshift-ci/build-root/Dockerfile
- scripts/openshiftci-presubmit-devfiles-odo-all-tests.sh
- scripts/openshiftci-presubmit-devfiles-odo-tests.sh
> Update Odo integration tests

- scripts/openshiftci-presubmit-devfiles-odo-all-tests.sh
- scripts/openshiftci-presubmit-devfiles-odo-tests.sh
Fix integration tests to reflect the change in odo codes. 
fixes https://github.com/devfile/api/issues/893
> Update CI integration tests

- scripts/openshiftci-presubmit-devfiles-odo-tests.sh
Remove unnecessary 'go install' in the test script file
> Remove unnecessary line in test script

- scripts/openshiftci-presubmit-devfiles-odo-tests.sh
Add more odo tests with devfiles for nightly test.
> Run more odo tests with devfiles

- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
- scripts/openshiftci-presubmit-devfiles-odo-tests.sh
- tests/odo/test_create_cmd.py
Add devfile test with ODC for the newly added sample devfiles.
Fixes https://github.com/devfile/api/issues/975
It's tested in a local environment.
> Add more devfile samples test with ODC

- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
> Update sample devfile test with odc

- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
> Revert changes made to ODC tests

- tests/odo_300/test_init_cmd.py
> Fix to use test devfile registry for tests

- .ci-operator.yaml
- openshift-ci/build-root/Dockerfile
> Update build root to use Go 1.18 image

- scripts/console/frontend/packages/dev-console/integration-tests/features/addFlow/create-from-devfile.feature
Update a sample repository used for test to fix the failed integration tests.
> Update a sample repository used for test

- OWNERS
Updates the OWNERS file with the new members of devfile team
this task is part of devtools week
This PR only updates the OWNERS file
> [Devtools Week] Update OWNERS file with new members

- .github/workflows/gotest.yaml
This PR adds slack notification step to the `devfile go integration tests` workflow.
Fixes https://github.com/devfile/api/issues/1026
> Add slack notification for devfile go integration tests
